// Seed data for 공통수학1 (2022 개정) curriculum
// Maps: 중단원 -> Unit, 소단원 -> Lesson

import { Unit, Lesson, UnitTheme } from "./types";

export interface SeedUnit extends Omit<Unit, "id"> {
  id: string;
}

export interface SeedLesson extends Omit<Lesson, "id"> {
  id: string;
}

// ==================== 공통수학1 Units (중단원) ====================

export const commonMath1Units: SeedUnit[] = [
  // 대단원 1: 다항식
  {
    id: "cm1_1_1",
    title: "다항식의 연산",
    description: "다항식의 사칙연산, 나눗셈, 곱셈공식을 학습합니다",
    subject: "공통수학1",
    order: 1,
    emoji: "📐",
    theme: "blue" as UnitTheme,
  },
  {
    id: "cm1_1_2",
    title: "항등식과 나머지정리",
    description: "항등식의 성질과 나머지정리, 인수정리를 학습합니다",
    subject: "공통수학1",
    order: 2,
    emoji: "🔍",
    theme: "blue" as UnitTheme,
  },
  {
    id: "cm1_1_3",
    title: "인수분해",
    description: "다양한 인수분해 공식과 방법을 학습합니다",
    subject: "공통수학1",
    order: 3,
    emoji: "🧩",
    theme: "blue" as UnitTheme,
  },

  // 대단원 2: 방정식과 부등식
  {
    id: "cm1_2_1",
    title: "복소수",
    description: "허수단위와 복소수의 개념, 사칙연산을 학습합니다",
    subject: "공통수학1",
    order: 4,
    emoji: "💫",
    theme: "green" as UnitTheme,
  },
  {
    id: "cm1_2_2",
    title: "이차방정식",
    description: "이차방정식의 근의 판별과 근과 계수의 관계를 학습합니다",
    subject: "공통수학1",
    order: 5,
    emoji: "🎯",
    theme: "green" as UnitTheme,
  },
  {
    id: "cm1_2_3",
    title: "이차함수와 이차방정식",
    description: "이차함수와 이차방정식의 관계, 최대/최소를 학습합니다",
    subject: "공통수학1",
    order: 6,
    emoji: "📈",
    theme: "green" as UnitTheme,
  },
  {
    id: "cm1_2_4",
    title: "고차방정식",
    description: "고차방정식의 풀이와 삼차방정식의 근과 계수의 관계를 학습합니다",
    subject: "공통수학1",
    order: 7,
    emoji: "🏔️",
    theme: "green" as UnitTheme,
  },
  {
    id: "cm1_2_5",
    title: "연립방정식",
    description: "연립이차방정식과 부정방정식을 학습합니다",
    subject: "공통수학1",
    order: 8,
    emoji: "🔗",
    theme: "orange" as UnitTheme,
  },
  {
    id: "cm1_2_6",
    title: "부등식",
    description: "일차부등식, 연립부등식, 절댓값 부등식을 학습합니다",
    subject: "공통수학1",
    order: 9,
    emoji: "⚖️",
    theme: "orange" as UnitTheme,
  },
  {
    id: "cm1_2_7",
    title: "이차부등식",
    description: "이차부등식과 연립이차부등식, 실근의 조건을 학습합니다",
    subject: "공통수학1",
    order: 10,
    emoji: "📊",
    theme: "orange" as UnitTheme,
  },

  // 대단원 3: 경우의 수
  {
    id: "cm1_3_1",
    title: "경우의 수",
    description: "합의 법칙, 곱의 법칙, 순열, 조합을 학습합니다",
    subject: "공통수학1",
    order: 11,
    emoji: "🎲",
    theme: "purple" as UnitTheme,
  },

  // 대단원 4: 행렬
  {
    id: "cm1_4_1",
    title: "행렬",
    description: "행렬의 뜻과 연산, 곱셈을 학습합니다",
    subject: "공통수학1",
    order: 12,
    emoji: "🔢",
    theme: "red" as UnitTheme,
  },
];

// ==================== 공통수학1 Lessons (소단원) ====================

export const commonMath1Lessons: SeedLesson[] = [
  // 1.1 다항식의 연산
  {
    id: "cm1_1_1_1",
    unitId: "cm1_1_1",
    title: "다항식의 사칙연산",
    description: "다항식의 덧셈, 뺄셈, 곱셈을 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["다항식 덧셈", "다항식 뺄셈", "다항식 곱셈", "동류항"],
  },
  {
    id: "cm1_1_1_2",
    unitId: "cm1_1_1",
    title: "다항식의 나눗셈",
    description: "다항식을 다항식으로 나누는 방법을 학습합니다",
    order: 2,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["다항식 나눗셈", "몫", "나머지", "조립제법"],
  },
  {
    id: "cm1_1_1_3",
    unitId: "cm1_1_1",
    title: "곱셈공식",
    description: "자주 쓰이는 곱셈공식을 익힙니다",
    order: 3,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["완전제곱식", "합차공식", "곱셈공식"],
  },
  {
    id: "cm1_1_1_4",
    unitId: "cm1_1_1",
    title: "곱셈공식의 변형",
    description: "곱셈공식을 변형하여 다양한 문제에 적용합니다",
    order: 4,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["곱셈공식 변형", "대칭식", "교대식"],
  },

  // 1.2 항등식과 나머지정리
  {
    id: "cm1_1_2_1",
    unitId: "cm1_1_2",
    title: "항등식과 미정계수",
    description: "항등식의 성질과 미정계수법을 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["항등식", "미정계수법", "수치대입법", "계수비교법"],
  },
  {
    id: "cm1_1_2_2",
    unitId: "cm1_1_2",
    title: "나머지정리와 인수정리",
    description: "나머지정리와 인수정리를 이해하고 활용합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["나머지정리", "인수정리", "다항식의 나눗셈"],
  },

  // 1.3 인수분해
  {
    id: "cm1_1_3_1",
    unitId: "cm1_1_3",
    title: "인수분해 공식",
    description: "기본적인 인수분해 공식을 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["인수분해", "공통인수", "완전제곱식", "합차공식"],
  },
  {
    id: "cm1_1_3_2",
    unitId: "cm1_1_3",
    title: "여러 가지 인수분해",
    description: "복잡한 다항식의 인수분해 방법을 학습합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["치환 인수분해", "복이차식", "인수정리 활용"],
  },

  // 2.1 복소수
  {
    id: "cm1_2_1_1",
    unitId: "cm1_2_1",
    title: "허수단위와 복소수",
    description: "허수단위 i와 복소수의 개념을 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["허수단위", "복소수", "실수부", "허수부"],
  },
  {
    id: "cm1_2_1_2",
    unitId: "cm1_2_1",
    title: "복소수의 사칙연산",
    description: "복소수의 덧셈, 뺄셈, 곱셈, 나눗셈을 학습합니다",
    order: 2,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["복소수 덧셈", "복소수 곱셈", "켤레복소수", "복소수 나눗셈"],
  },
  {
    id: "cm1_2_1_3",
    unitId: "cm1_2_1",
    title: "음수의 제곱근",
    description: "음수의 제곱근과 그 성질을 학습합니다",
    order: 3,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["음수의 제곱근", "i의 거듭제곱", "복소수의 성질"],
  },

  // 2.2 이차방정식
  {
    id: "cm1_2_2_1",
    unitId: "cm1_2_2",
    title: "이차방정식의 근의 판별",
    description: "판별식을 이용하여 근의 종류를 판별합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["판별식", "실근", "허근", "중근"],
  },
  {
    id: "cm1_2_2_2",
    unitId: "cm1_2_2",
    title: "근과 계수의 관계",
    description: "이차방정식의 근과 계수 사이의 관계를 학습합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "advanced",
    concepts: ["근과 계수의 관계", "두 근의 합", "두 근의 곱"],
  },

  // 2.3 이차함수와 이차방정식
  {
    id: "cm1_2_3_1",
    unitId: "cm1_2_3",
    title: "이차함수와 이차방정식의 관계",
    description: "이차함수의 그래프와 이차방정식의 관계를 학습합니다",
    order: 1,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["이차함수 그래프", "x축과의 교점", "판별식과 그래프"],
  },
  {
    id: "cm1_2_3_2",
    unitId: "cm1_2_3",
    title: "이차함수의 최대, 최소",
    description: "이차함수의 최댓값과 최솟값을 구합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["꼭짓점", "최댓값", "최솟값", "완전제곱식"],
  },

  // 2.4 고차방정식
  {
    id: "cm1_2_4_1",
    unitId: "cm1_2_4",
    title: "고차방정식의 풀이",
    description: "삼차 이상의 방정식을 인수분해하여 풀이합니다",
    order: 1,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["삼차방정식", "사차방정식", "인수정리 활용", "조립제법"],
  },
  {
    id: "cm1_2_4_2",
    unitId: "cm1_2_4",
    title: "삼차방정식의 근과 계수와의 관계",
    description: "삼차방정식에서 근과 계수의 관계를 학습합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["세 근의 합", "세 근의 곱", "근과 계수의 관계"],
  },
  {
    id: "cm1_2_4_3",
    unitId: "cm1_2_4",
    title: "오메가의 성질",
    description: "1의 세제곱근 오메가의 성질을 학습합니다",
    order: 3,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "expert",
    concepts: ["오메가", "1의 세제곱근", "허근의 성질"],
  },

  // 2.5 연립방정식
  {
    id: "cm1_2_5_1",
    unitId: "cm1_2_5",
    title: "연립이차방정식",
    description: "이차식을 포함한 연립방정식을 풀이합니다",
    order: 1,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["연립이차방정식", "대입법", "가감법"],
  },
  {
    id: "cm1_2_5_2",
    unitId: "cm1_2_5",
    title: "부정방정식",
    description: "해가 무수히 많은 부정방정식을 학습합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "advanced",
    concepts: ["부정방정식", "정수해", "자연수해"],
  },

  // 2.6 부등식
  {
    id: "cm1_2_6_1",
    unitId: "cm1_2_6",
    title: "부등식의 성질과 일차부등식",
    description: "부등식의 기본 성질과 일차부등식을 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["부등식의 성질", "일차부등식", "해집합"],
  },
  {
    id: "cm1_2_6_2",
    unitId: "cm1_2_6",
    title: "연립일차부등식",
    description: "연립일차부등식의 풀이를 학습합니다",
    order: 2,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["연립일차부등식", "공통범위", "수직선"],
  },
  {
    id: "cm1_2_6_3",
    unitId: "cm1_2_6",
    title: "절댓값이 있는 일차부등식",
    description: "절댓값을 포함한 일차부등식을 풀이합니다",
    order: 3,
    xpReward: 25,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "advanced",
    concepts: ["절댓값", "절댓값 부등식", "경우 나누기"],
  },

  // 2.7 이차부등식
  {
    id: "cm1_2_7_1",
    unitId: "cm1_2_7",
    title: "이차부등식",
    description: "이차부등식의 풀이를 학습합니다",
    order: 1,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["이차부등식", "이차함수 그래프", "부등식의 해"],
  },
  {
    id: "cm1_2_7_2",
    unitId: "cm1_2_7",
    title: "연립이차부등식",
    description: "연립이차부등식의 풀이를 학습합니다",
    order: 2,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "advanced",
    concepts: ["연립이차부등식", "공통범위", "수직선"],
  },
  {
    id: "cm1_2_7_3",
    unitId: "cm1_2_7",
    title: "이차방정식의 실근의 조건",
    description: "이차방정식이 실근을 가질 조건을 학습합니다",
    order: 3,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "expert",
    concepts: ["판별식", "실근의 조건", "이차부등식 활용"],
  },

  // 3.1 경우의 수
  {
    id: "cm1_3_1_1",
    unitId: "cm1_3_1",
    title: "합의 법칙과 곱의 법칙",
    description: "경우의 수의 기본 원리를 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["합의 법칙", "곱의 법칙", "경우의 수"],
  },
  {
    id: "cm1_3_1_2",
    unitId: "cm1_3_1",
    title: "순열",
    description: "순열의 뜻과 계산 방법을 학습합니다",
    order: 2,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["순열", "팩토리얼", "nPr", "원순열"],
  },
  {
    id: "cm1_3_1_3",
    unitId: "cm1_3_1",
    title: "조합",
    description: "조합의 뜻과 계산 방법을 학습합니다",
    order: 3,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["조합", "nCr", "이항계수", "조합의 성질"],
  },

  // 4.1 행렬
  {
    id: "cm1_4_1_1",
    unitId: "cm1_4_1",
    title: "행렬의 뜻",
    description: "행렬의 개념과 용어를 학습합니다",
    order: 1,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["행렬", "성분", "행", "열", "영행렬", "단위행렬"],
  },
  {
    id: "cm1_4_1_2",
    unitId: "cm1_4_1",
    title: "행렬의 덧셈, 뺄셈, 실수배",
    description: "행렬의 기본 연산을 학습합니다",
    order: 2,
    xpReward: 20,
    estimatedMinutes: 15,
    type: "standard",
    difficulty: "beginner",
    concepts: ["행렬의 덧셈", "행렬의 뺄셈", "실수배", "행렬의 상등"],
  },
  {
    id: "cm1_4_1_3",
    unitId: "cm1_4_1",
    title: "행렬의 곱셈",
    description: "행렬의 곱셈과 그 성질을 학습합니다",
    order: 3,
    xpReward: 25,
    estimatedMinutes: 20,
    type: "standard",
    difficulty: "intermediate",
    concepts: ["행렬의 곱셈", "교환법칙 불성립", "결합법칙"],
  },
];
