// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBruskq02tYP7wIOlCgxG76X3GC1SsExgQ',
    appId: '1:421762663548:web:mathlab-gomath',
    messagingSenderId: '421762663548',
    projectId: 'mathlab-gomath',
    authDomain: 'mathlab-gomath.firebaseapp.com',
    storageBucket: 'mathlab-gomath.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruskq02tYP7wIOlCgxG76X3GC1SsExgQ',
    appId: '1:421762663548:android:mathlab-gomath',
    messagingSenderId: '421762663548',
    projectId: 'mathlab-gomath',
    storageBucket: 'mathlab-gomath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBruskq02tYP7wIOlCgxG76X3GC1SsExgQ',
    appId: '1:421762663548:ios:mathlab-gomath',
    messagingSenderId: '421762663548',
    projectId: 'mathlab-gomath',
    storageBucket: 'mathlab-gomath.firebasestorage.app',
    iosBundleId: 'com.gomath.mathlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBruskq02tYP7wIOlCgxG76X3GC1SsExgQ',
    appId: '1:421762663548:macos:mathlab-gomath',
    messagingSenderId: '421762663548',
    projectId: 'mathlab-gomath',
    storageBucket: 'mathlab-gomath.firebasestorage.app',
    iosBundleId: 'com.gomath.mathlab',
  );
}
